---
version: "3"
services:
  influx:
    image: tutum/influxdb

  grafana:
    image: grafana/grafana
    links:
      - influx
    depends_on:
      - influx
    ports:
      - 3000

  grokodile:
    build: .
    links:
      - influx
    depends_on:
      - influx
    ports:
      - 8000
